spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/neighbourly
spring.datasource.username=neighbourly
spring.datasource.password=dev
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect